spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/library2_db
    username: postgres
    password: dima02wer
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/changelog-master.yaml
logging:
  level:
    root: INFO
